### ISSUE TITLE
Error 403 from Google

### ISSUE THREAD

**Issue by kk143g** [maximbilan/SwiftGoogleTranslate#2]
Hi, am trying to use this library to translate text, but am getting error 403, even i have billing account of Google and using API key from that account, even though translation API is enabled.

**Comment by maximbilan** [comment]
Thanks for the report. Please make sure that you're the correct API key.

**Comment by kk143g** [comment]
Yes am using the correct API kay,

**Comment by maximbilan** [comment]
Check out this page to set up your configuration correctly in Google API settings https://cloud.google.com/translate/troubleshooting

**Comment by kk143g** [comment]
I have configured all things, billing is enabled, daily quota limit is not exceeded, But still am getting 403 error. Any idea?

**Comment by maximbilan** [comment]
Did you try to change the version of requests to `v3`?
The framework uses `v2`
```

**Comment by maximbilan** [comment]
Did you try to change the version of requests to `v3`?
The framework uses `v2` as it was created a long time ago.
```
https://translation.googleapis.com/language/translate/v2
```
You can check your API key sending requests using Postman to the API and make sure that your configuration is set up correctly.
