### ISSUE TITLE
TMS-90535: Unexpected CFBundleExecutable Key at AppStore

### ISSUE THREAD

**Issue by ymatt345** [maximbilan/SwiftGoogleTranslate#3]
Hi
I uploaded my App to AppStore for test Flight and got the following error message.
TMS-90535: Unexpected CFBundleExecutable Key - The bundle at '/Payload/WEShadowing.app/SwiftGoogleTranslate/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

excutable file was set as ${EXECUTABLE_NAME} 
I tried to removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL, then my app was not able to install yo my device.
According to the Apple error message , I thought  that I should contact to you.
Please give me of your advice.
Thank you,

**Comment by maximbilan** [comment]
The package doesn't contain `Info.plist`. Make sure that `Info.plist` of your project is set up properly.

**Comment by ymatt345** [comment]
I could observe two info.plist in your package.
The location of the info.plists are follows.
Please check the info.plist in your package again.

I am using xCode 13.3 and AppStore rejected my app due to  swiftGoogleTranslate/info.plist 
If so no app using SwiftGoogleTranslate would pass AppStore.

The locations of info.plist.
1. AppFolder/SwiftGoogleTranslate/info.plist
   AppFolder/SwiftGoogleTranslate/SwiftGoogleTranslate.h  //  It may easy to understand location of SwiftGoogleTranslate.h 
2. Pods/Pods/SwiftGoogleTranslate/Support Files/SwiftGoogleTranslate-Info.plist

The 1. and 2. of info.plist  looks same.
If you do not contain info.plist , please advice us how to remove these info.plist
Best regards,
